### ISSUE TITLE
Best practices for calling Tibber API

### ISSUE THREAD

**Issue by toini** [dinmammas/homebridge-tibberswitch#1]
Hi!

I would like to thank you for contributing to the community of Tibber users! We've added you to the list of people we respect! https://developer.tibber.com/respect

We noticed your library is polling for prices every ten minutes which is rather not optimal especially if this library gets installed by many people. The prices are updated once per day (around 13 CET) so you could attempt to fetch them often around that time and then stop until the next day?

Also, it looks like you are not setting user-agent header value. You could possibly do that [here](https://github.com/dinmammas/homebridge-tibberswitch/blob/main/index.js#L75)

A recommended format would be to include both the platform version and driver version like this:
'User-Agent': 'Homebridge/1.2.3 homebridge-tibberswitch/0.0.23' 

We're trying to collect best practices [here](https://developer.tibber.com/docs/guides/calling-api)

Let us know if in need of any assistance!

Br,
Toni 
Tibber

**Comment by dinmammas** [comment]
Hi Toni!
Thanks for the kind words.

Improvements are already on the way :) 

I'll add caching and refreshing of the data, and headers to the to-do list. It's not gonna be done before next week, I hope that's OK. If not, feel free to do a pull request ;)

Br,
David

P.S. It's not my plugin that's listed on the respect page (but that's not important) ;) D.S.

**Comment by toini** [comment]
We've updated the list now ;)

**Comment by dinmammas** [comment]
Thnx @toini

I have a beta version ready with the desired changes. I'll let it run for a day or two before I publish to the masses.

**Comment by dinmammas** [comment]
You should be seeing requests with this user agent now:`"User-Agent": "Homebridge/1.5.1 homebridge-tibberswitch/0.2.0 node/16.15.0`

**Comment by toini** [comment]
Awesome!

**Comment by dinmammas** [comment]
Version 0.3.0 now live.
