### ISSUE TITLE
Setting to have motion sensor activated on {price and *higher*}

### ISSUE THREAD

**Issue by napthemax** [dinmammas/homebridge-tibberswitch#2]
Suggestion for a possible enhancement in the future; possibility to have the motion sensor activated if the price is *above* the set threshold (the other way around as it is now). I know I can do a reverse automation in Homekit, but i think there is more understandable to create the action if the motion sensor is on if the price is high. And I can have a lamp turning ON telling my kids not to shower for 40 minutes ...

**Comment by dinmammas** [comment]
I'm thinking you could have the lamp as red by default, and change it to green if the price is low?

But I'm guessing you'd like it completely off when the price is low? Which is doable too tho...

**Comment by napthemax** [comment]
> I'm thinking you could have the lamp as red by default, and change it to green if the price is low?
> 
> But I'm guessing you'd like it completely off when the price is low? Which is doable too tho...

Yeah, it's not the most prioritized issue for me, but I think it's easier for most to create automations if the behaviour in tibbeswitch tells the user what it will do. Now I have a red lamp programmed to be **ON** when the sensor reports **OFF**. Works for me, but could be confusing for others.
