### ISSUE TITLE
Support for multiple homes

### ISSUE THREAD

**Issue by napthemax** [dinmammas/homebridge-tibberswitch#3]
I have two homes with Tibber in different electricity areas (SE2 & SE3). Would like to have a tibberswitch in both homes (similar functionality as in iOSTibberWidget where I select home in the config file).

**Comment by dinmammas** [comment]
This is in my roadmap already :)

**Comment by dinmammas** [comment]
Better late than never.
Version 0.3.2 is out and it _should_ support selection of homes. Please try it out and report back. I've only got one home, so it's a bit tricky to test it myself. 😅

**Comment by napthemax** [comment]
> ... Please try it out and report back ...

Thanks, will do as soon as Hoobs mirrors the update (don't want to manually update since Hoobs does things slightly different than Homebridge apparently).

**Comment by napthemax** [comment]
Working just fine. Main home in Tibber [Home: 0];

![image](https://github.com/dinmammas/homebridge-tibberswitch/assets/22963382/afe6b8ed-de14-430b-95a8-98df7cb87c22)

And the summer house [Home: 1]:

![image](https://github.com/dinmammas/homebridge-tibberswitch/assets/22963382/633001d0-03d1-492e-b8ad-b66e2f1a72cd)

Next on wishlist; select currency ;-)

**Comment by dinmammas** [comment]
Nice! Thanks for testing!
